spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telegram-webapp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: root
    password: root
    default-schema: telegram-webapp


